repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-symlinks
  - id: trailing-whitespace
  - id: check-json
  - id: check-yaml
  - id: pretty-format-json
    args: [--autofix]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
  - id: mypy
- repo: https://github.com/PyCQA/isort
  rev: 5.13.1
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.1
  hooks:
  - id: autoflake
    exclude: __init__.py
    args:
    - --in-place
    - --remove-unused-variables
    - --remove-all-unused-imports
